bin/build.sh
During the Docker build process, it pulls in the theme and then runs NPM
to compile the assets. This change has been modified to run the correct
NPM commands for Nightingale theme, however, in future we may want to
either change the command in the theme or add further conditionals for
other themes in MS.
=>  Build Nightingale assets using theme NPM cmd

composer.lock
This pulls in the most recent version of the MOJ Blocks plugin, which now includes the staggered box.
=> Add version of MOJ Blocks that includes staggered box

composer.lock
Also bumps wordpress up to  5.5.1
=> Update Plugins and Theme

composer.lock
This is so that I can get this on staging to test with my windows laptop!
=> Pull in new MOJ blocks with high contrast mode update, for testing

composer.lock
Pulls in the new Nightingale theme style update, to fix the styling bug
=> Update Nightingale theme version

composer.json, composer.lock
=> Add Hale Theme

composer.lock
This pulls in updated versions of Hale and the cookie banner plugin. 
The Hale update pulls in updated focus styles, and the cookie banner update pulls in a fix to a visual bug.
=> Pull in hale focus states update and cookie banner bug fix

composer.json, composer.lock
MoJ blocks are now version controlled so this change accounts for that as well.
=> Update Composer to refect MoJ Block changes

composer.lock, config/application.php, docker-compose.yml
Modifies the constant: `WP_DEFAULT_THEME` to define the new theme.
Upgrades WP to the new version: `5.5.3`
=> Change default-theme to hale + php software update

composer.lock
Hale theme updates include
Remove full width template
Remove unused Dockerfile
General clean-up of text files
=> Update Hale theme

composer.lock
This makes sure that the latest accessibility updates are pulled in
=> Update to hale version 1.0.9

composer.lock
This pulls in more accessibility and bug fixes.
=> Update the cookie banner, and Hale to 1.0.10

composer.lock
This pulls in an update to the meta tags, to help with google search results for our sites.
=> Update hale to 1.0.11

composer.lock
This pulls in the latest cookie banner version
=> Pull in cookie banner 2.0.1

composer.lock
* Add in dynamic block refactor
=> Update composer wp moj block change to quotes

composer.lock
* Changes to Hale theme footer
=> Update Composer to reflect Hale changes

buildspec.yml, composer.lock
Docker images were previously accessed annoymously causing us to reach
Docker's 100 pull limit. This change uses the MoJ account providing for
unlimited pulls.
=> Update Composer & update build to auth DockerHub

composer.json, composer.lock, web/app/mu-plugins/moj/acf-json/group_61a6103e68ef5.json
=> acf plugin

composer.json, composer.lock, config/application.php
* Check on Sentry install.
* Update of Composer packages
=> Wrap check on sentry code to check sentry install

composer.json, composer.lock, web/app/mu-plugins/moj/acf-json/group_634fab68ec137.json
WP has been set 6.0.3 so we can control rolling out 6.1.0
=> Update Hale, Update Doc Listing ACF Fields, Set WP to 6.0.3

composer.lock
=> composer.lock
